controller_server:
  ros__parameters:
    use_sim_time: True
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      rotate_to_heading_angular_vel: 1.8

      critics: 
        - "path_critic"
        - "goal_critic"

      path_critic:
        plugin: "nav2_path_critic::PathCritic"
        tolerance: 0.2

      goal_critic:
        plugin: "nav2_goal_critic::GoalCritic"
        tolerance: 0.5
