local_costmap:
  ros__parameters:
    use_sim_time: True
    global_frame: /blueye/odom
    robot_base_frame: blueye_link
    update_frequency: 5.0
    publish_frequency: 2.0
    resolution: 0.05
    size_x: 10.0
    size_y: 10.0
    plugins: ["obstacle_layer", "inflation_layer"]

    obstacle_layer:
      enabled: True
      max_obstacle_height: 2.0
      obstacle_range: 5.0
      raytrace_range: 6.0
      observation_sources: laser
      laser:
        sensor_frame: lidar_frame
        data_type: "LaserScan"
        topic: /blueye/sonar
        marking: True
        clearing: True

    inflation_layer:
      inflation_radius: 0.5
      cost_scaling_factor: 2.0
