recovery_server:
  ros__parameters:
    use_sim_time: True
    recovery_plugins: ["spin", "backup"]

    spin:
      plugin: "nav2_recoveries/Spin"
      enabled: True

    backup:
      plugin: "nav2_recoveries/BackUp"
      enabled: True
